# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d42802455a3cd67b316b76fec9d2a3d6ee0d8b98460a4d1d3419fcb0a57161db23a99eb2f06c60733a92af7503050097120e7c93105253624c9554e2a2f0e74

test:
  secret_key_base: 03de689886fa765b6fb960470d2d05da367f84e00e4f61b4130e85e16ab261be1d7e0976f345d98114c8b758c443001d26ff1a90064a091d5de11619e21ec0c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
